# Problem Statement: Grocery Receipt

# You are required to implement a class GroceryReceipt that extends GroceryReceiptBase 
# for an e-commerce company's billing software.

# Given:
$ A list of unique fruits with their prices (prices).
$ A list of unique fruits with their discounts (discounts).
$ A list of items purchased by a user and their quantities (shoppingList, may contain duplicates).

# Task
# Generate the final invoice with the format: Item name, Price per unit, Total price after applying discounts
$ Total Price is calculated as quantity × price, minus any applicable discount.
$ The invoice list should be sorted in ascending order by product name.

# GroceryReceipt class:

$ Implement GroceryReceipt class that extends GroceryReceiptBase 
$ These properties are are passed on instantiation:
	$  prices - the List of fruits (String) and their prices (Double)
	$ discounts - the List of discounts (Integer) for each fruit (String)
$ Implement a Calculate Method:
	$ It receives a list of fruits and quantities called shoppingList.
	$ It returns a list of fruit names (String), the original price per unit (Integer), and 
	$ the total price after discounts (Double) for the items in the shopping list in ascending order by fruit name.

# Example:
$ prices = [["Banana", 10], ["Apple", 20], ["Orange", 5]] as [item (String), price (Double)].
$ discounts = [["Orange", 10]] as [item (String), discount percent (Integer)].
$ shoppingList = [["Banana", 5], ["Orange", 2], ["Orange", 1]] as [item (String), quantity (Integer)].

*************************Invoice*************************
item			price			total_price
Banana		10				50
Orange		5					13.5

# Normally, an Orange costs 5 per unit, but there is a 10% discount. 
# For 3 units of Orange, the gross price is 15, less 10% is 13.5. 
# Order them alphabetically and return [["Banana", 10, 50], ["Orange", 5, 13.5]].

# Function Description:
# Create GroceryReceipt class by extending the GroceryReceiptBase abstract class. 
# Implement a Calculate function to create invoices. 
# The function should return:
	# the item name, quantity, and the total price after the discount for every item in the Shopping List.
	
# Sample Input 1:
# STDIN										# Function
3									-->			number of prices n = 3		
Apple 34  				    -->           [fruit, price per unit] = [["Apple", 34], 
Banana 14  																		  ["Banana", 14], 
Orange 4  																			  ["Orange", 4]]

1									-->			number of discounts m = 1		
Orange 10  			    -->           [fruit, percentage discount] = [["Orange", 10]]

2									-->			number of items in shoppingList k = 2		
Apple 2  				        -->           [fruit, units] = [["Apple", 2], ["Apple", 5]]
Apple 5 

# Sample Output 2:
Apple 34.0 238.0  

# Explanation:
# The shopping list is 2 units Apple and 5 units Apple.
# 7 units of Apple cost 7*34 = 238 and there is no discount.

# Sample Input 2:
# STDIN										# Function
3									-->			number of prices n = 3		
Apple 31  				    -->           [fruit, price per unit] = [["Apple", 31], 
Banana 39  																		  ["Banana", 39], 
Orange 47  																		  ["Orange", 47]]

3									-->			number of discounts m = 3		
Apple 40      			    -->           [fruit, percentage discount] = [["Apple", 40]]
Banana 40																						  ["Banana", 40],
Orange 40																						  ["Orange", 50],

2									-->			number of items in shoppingList k = 2		
Banana 4  				    -->           [fruit, units] = [["Banana", 4], ["Apple", 3]]
Apple 3 

# Sample Output 2:
Apple 31.0 55.8  
Banana 39.0 93.6

# Explanation:
# The shopping list is 3 units of Apple and 4 units of Banana.
# There is 40% of discount on both items.

# Apple: 3 * 31 = 93, less 40% is 55.8.
# Banana: 4 * 39 = 156, less 40% is 93.6.