# Problem Statement: Minimum Good Subarray

# For an array of n positive integers arr[n] and an integer k,
# a subarray is considered good if it contains at least k distinct integers.

# Requirements:
$ Find the minimum length subarray that is good.
$ If there is no such subarray exists, return -1.

# Function Description
$ Complete the function findMinimumLengthSubarray:
$ int findMinimumLengthSubarray(int[] arr, int k)

# Parameters:
$ int arr[n]: the array of positive integers.
$ int k: the minimum number of distinct elements a good subarray must contain.

# Returns:
$ int: the minimum length possible for a good subarray, or
$ -1 if no such subarray exists.
 
 # Constraints
$ 1 <= n <= 10^5.
$ 1 <= arr[i] <= 10^6
$ 1 <= k <= n.

# Input Format
$ The first line contains an integer, n, the number of elements in arr.
$ Each line i of the n subsequent lines (where 0 <= i < n) contains an integer, arr[i].
$ The next line contains a single integer, k.

# Output Format
$ Print the name of the student with the highest rank, 
$ followed by the student with the lowest rank, separated by a comma.

# Sample Test Case 0:
# Sample Input 1:
# STDIN										# Function
6									-->			n = 6		
3				  				    -->           arr = [3, 2, 3, 3, 1, 3] 
2
3
3
1
3
3									-->			k = 6

# Output:
4

# Sample Test Case 1:
# Sample Input 2:
# STDIN										# Function
5									-->			n = 5		
1				  				    -->           arr = [1, 2, 2, 1, 2] 
2
2
1
2
4									-->			k = 4

# Output:
-1

# Explanation:
$ For arr = [1, 2, 2, 1, 2], there is no subarray that contains at least 4 distinct integers.